#!/usr/bin/python3
import argparse
import logging
import sys
sys.path.append('../')
import odbPreprocessor
import re
import CppGenerator
from CppGenerator import TypeRegistry

def camelCase(el):
    retVal=[el[0].upper()+el[1:]]
    return "".join(retVal)

def defaultValues(dType):
  m=re.match('.*\((.*)\).*',dType)
  pType=dType.replace('(%s)'%(m.group(1)),'()') if m else dType
  DefaultVals={
                "int"     : "1",
                "float"   : "1.2345",
                "double"  : "2.4680",
                "text"    : '"abc"',
                "char"    : "'x'",
                "char()"  : '"abc"',
                "bigint"  : "100",
                "long"    : "9999",
              };
  retVal=DefaultVals[pType];
  return retVal

class TestObj:
  def __init__(self,id,name,objList):
    self.id_=id
    self.name_=name
    self.tests_=[]
    self.objList_=objList
    self.testNames_=[]
    self.tests_+=self.simpleTest()
    self.tests_+=self.randomTest()

  def objCtor(self,objName):
    L=[]
    pKeys=[el for el in self.objList_ if el.isKey]
    pKey=pKeys[0]
    i=0
    pKeyList=[]
    for pKey in pKeys:
      dType=TypeRegistry.typeConverter(pKey.type) if TypeRegistry.isPrimitiveType(pKey.type) else "%s::%s"%(self.name_,TypeRegistry.typeConverter(pKey.type))
      keyVarName='pKey%d'%(i)
      pKeyList.append(keyVarName)
      if pKey.type in ['int','float','double','text','char','bigint','long']:
        L.append("%s %s;"%(dType,'%s=%s'%(keyVarName,defaultValues(pKey.type))))
      else:
        L.append("%s %s;"%(dType,'%s(%s)'%(keyVarName,defaultValues(pKey.type))))
      i+=1
    L.append("%s %s(%s);"%(self.name_,objName,','.join(pKeyList)))
    return L

  def objSetter(self, el,val):
    fxn="set"+el.name[0].upper()+el.name[1:]
    return ['obj.%s(%s);'%(fxn,val)]

  def objGetter(self, el):
    fxn="get"+el.name[0].upper()+el.name[1:]
    return ['obj.%s()'%(fxn)]

  def simpleTest(self):
    L=[]
    fxnName='test%05d'%(self.id_)
    fxnName='test%sSimpleTest'%(self.name_)
    self.testNames_.append("")
    L.append('void %s()'%(fxnName))
    L.append('{')
    L.append('  dropTable("%s");'%(self.name_))
    for e in self.objCtor('obj'):
      L.append('  %s'%(e))
    mutableFields=[el for el in self.objList_ if not el.isKey]
    for e in mutableFields:
      L.append('  {')
      newVar='newVal'
      if e.type in ['float','bigint','text','char','int','long','double','date','datetime']:
        varDeclaration=TypeRegistry.typeConverter(e.type) if TypeRegistry.isPrimitiveType(e.type) else "%s::%s"%(self.name_,TypeRegistry.typeConverter(e.type))
        L.append('    const %s %s=%s;'%(varDeclaration, newVar, defaultValues(e.type)))
      else:
        typeName="%s::%s"%(self.name_,CppGenerator.UserTypeGenerator.typeName(e.type))
        L.append('    const %s %s("");'%(typeName,newVar))
      for el in self.objSetter(e,newVar):
        L.append("    %s"%(el))
      for el in self.objGetter(e):
        L.append("    assert(%s==%s);"%(newVar,el))
      L.append("    {")
      L.append("      %s obj2(pKey0);"%(self.name_))
      obj1Getter=''.join(self.objGetter(e))
      obj2Getter=obj1Getter.replace('obj','obj2')
      L.append("      assert(%s==%s);"%(obj1Getter,obj2Getter))
      L.append("    }")
      L.append('  }')
    L.append('}')
    L.append('')
    return L

  def randomTest(self):
    L=[]
    fxnName='test%05d'%(self.id_)
    fxnName='test%sRandomTest'%(self.name_)
    self.testNames_.append("")
    L.append('void %s()'%(fxnName))
    L.append('{')
    L.append('  dropTable("%s");'%(self.name_))
    pKeys=[el for el in self.objList_ if el.isKey]
    mutableFields=[el for el in self.objList_ if not el.isKey]
    vEl=pKeys[0]
    if TypeRegistry.isPrimitiveType(vEl.type):
      dType=TypeRegistry.typeConverter(vEl.type)
    else:
      dType="%s::%s"%(self.name_,TypeRegistry.typeConverter(vEl.type))
    L.append("  for(int i=0; i<10; ++i)")
    L.append("  {")
    if 'VarChar' in dType:
      L.append('    const %s pKey("%s");'%(dType,"abc"))
    else:
      L.append("    const %s pKey=%s;"%(dType,"rando%s()"%(camelCase(dType))))
    L.append("    %s obj(%s);"%(self.name_,'pKey'))
    for e in mutableFields:
      vType=TypeRegistry.typeConverter(e.type).replace("std::","")
      L.append("    for(int k=0; k<10; ++k)")
      L.append("    {")
      typeDef=TypeRegistry.typeConverter(e.type)
      if 'VarChar' in typeDef:
        typeDef="%s::%s"%(self.name_,typeDef)
      if 'VarChar' in typeDef:
        L.append('      const %s newVal("%s");'%(typeDef,"ABC"))
      else:
        L.append("      const %s newVal=rando%s();"%(typeDef,camelCase(vType)))
      L.append("      obj.set%s(newVal);"%(camelCase(e.name)))
      L.append("      assert(newVal==obj.get%s());"%(camelCase(e.name)))
      L.append("    }")
      L.append("    {")
      L.append("      %s obj2(pKey);"%(self.name_))
      L.append("      assert(obj2.get%s()==obj.get%s());"%(camelCase(e.name),camelCase(e.name)))
      L.append("    }")
    L.append("  }")
    L.append('}')
    L.append('')
    return L


class TestModule:
  def __init__(self,name,objList):
    self.name_=name
    self.tests_=[]
    logging.debug("test object: %s %s"%(name, objList))
    i=0
    tc=TestObj(i,name,objList)
    self.tests_+=tc.tests_

def processFiles(fileList):
  retVal=[]
  obj=odbPreprocessor.Odb()
  for file in fileList:
    logging.debug('processing %s'%(file))
    dbEls=obj.parseOdbFile(file)
    logging.debug('dbEls %s'%(dbEls))
    for k,v in dbEls.items():
      logging.debug('processing %s; %s'%(k,v))
      tObj=TestModule(k,v)
      retVal+=tObj.tests_
  return retVal

def helperFunctions():
  retVal=[]
  L.append("void dropTable(const std::string& tableName)")
  L.append("{");
  L.append("  try");
  L.append("  {");
  L.append('    DbConnector::instance()->execute("DROP TABLE " + tableName + ";");')
  L.append("  }");
  L.append("  catch(sql::SQLException e)");
  L.append("  {");
  L.append("  }");
  L.append("}");
  L.append("char randoChar()")
  L.append("{")
  L.append('  const std::string CHARACTERS = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";')
  L.append("  static std::random_device random_device;")
  L.append("  static std::mt19937 generator(random_device());")
  L.append("  static std::uniform_int_distribution<> distribution(0, CHARACTERS.size() - 1);")
  L.append("")
  L.append("  return(CHARACTERS[distribution(generator)]);")
  L.append("}")
  L.append("std::string randoString()")
  L.append("{")
  L.append("  const int length=100;")
  L.append('  const std::string CHARACTERS = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";')
  L.append("  static std::random_device random_device;")
  L.append("  static std::mt19937 generator(random_device());")
  L.append("  static std::uniform_int_distribution<> distribution(0, CHARACTERS.size() - 1);")
  L.append("")
  L.append("  std::string random_string;")
  L.append("  for (std::size_t i = 0; i < length; ++i)")
  L.append("  {")
  L.append("      random_string += CHARACTERS[distribution(generator)];")
  L.append("  }")
  L.append("  return random_string;")
  L.append("}")
  L.append("")
  L.append("float randoFloat()")
  L.append("{")
  L.append("  static std::default_random_engine e;")
  L.append("  static std::uniform_int_distribution<> dis(-32767,32767); // take care to avoid values that lose precision in equal comparison")
  L.append("  return float(dis(e))/1000.0;")
  L.append("}")
  L.append("")
  L.append("int randoInt()")
  L.append("{")
  L.append("  static std::default_random_engine e;")
  L.append("  static std::uniform_int_distribution<> dis(-32767,32767); ")
  L.append("  return dis(e);")
  L.append("}")
  L.append("")
  L.append("long randoLong()")
  L.append("{")
  L.append("  static std::default_random_engine e;")
  L.append("  static std::uniform_int_distribution<> dis(-32767,32767); ")
  L.append("  return dis(e);")
  L.append("}")
  L.append("")
  L.append("double randoDouble()")
  L.append("{")
  L.append("  static std::default_random_engine e;")
  L.append("  static std::uniform_int_distribution<> dis(-32767,32767); // take care to avoid values that lose precision in equal comparison")
  L.append("  return double(dis(e))/1000.0;")
  L.append("}")
  return retVal

#--main--
if __name__ == "__main__":
  parser=argparse.ArgumentParser(description='ODB precompiler')
  parser.add_argument('--verbose',action='store_true', default=False)
  parser.add_argument('--input',action='append',required=True, default=[])
  parser.add_argument('--outfile',action='store',required=True)
  args,unk = parser.parse_known_args()

  if args.verbose:
    logLevel=logging.DEBUG
  else:
    logLevel=logging.INFO
  logging.basicConfig(format='%(asctime)s [%(filename)s:%(lineno)s] %(levelname)s: %(message)s', datefmt='%Y-%m-%d %I:%M:%S %p',level=logLevel)

  tL=processFiles(args.input)

  L=[]
  L.append('#include "log4cxx/logger.h"')
  L.append('#include "log4cxx/basicconfigurator.h"')
  L.append('#include <chrono>')
  L.append('#include <random>')
  for e in args.input:
    L.append('#include "%s.h"'%(e.replace('.odb','')))
  for e in helperFunctions():
    L.append("%s"%(e))
  L.append('')
  L+=tL
  L.append('int main(int argc, char* argv[])')
  L.append('{')
  L.append('  using namespace log4cxx;')
  L.append('  using namespace log4cxx::helpers;')
  L.append('  BasicConfigurator::configure();')
  L.append('  LoggerPtr logger(Logger::getLogger("main"));')
  L.append('  const auto startTs{std::chrono::steady_clock::now()};')
  testFxns=[el for el in tL if re.match('.*void test.*()',el)]
  for e in testFxns:
    call=e.split(' ')[1]
    L.append('  %s;'%(call))
  L.append('  const auto stopTs{std::chrono::steady_clock::now()};')
  L.append('  const std::chrono::duration<double> elapsedSecs{stopTs - startTs};')
  L.append('  LOG4CXX_DEBUG(logger, "main process terminating; elapsed time(" << elapsedSecs.count() << ")");')


  L.append('  return(EXIT_SUCCESS);')
  L.append('}')
  L.append('')
  with open(args.outfile,'w') as fp:
    fp.write('\n'.join(L))
